django_todo_app/django_todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todos.urls'))
]

django_todo_app/todos/urls.py
from django.urls import path
from .views import TodoDelete, TodoList, add_todo

app_name='todo'
urlpatterns = [
    path('',TodoList.as_view(), name='list'),
    path('add/', add_todo, name='add'),
    path('delete/<int:pk>/', TodoDelete.as_view(), name='delete')
]

django_todo_app/todos/models.py
from django.db import models



class Todo(models.Model):
    name = models.CharField(max_length=100)
    place = models.CharField(max_length=80)
    due_date = models.DateTimeField()
    

django_todo_app/todos/views.py
from django.db import models
from django.shortcuts import render, redirect
from django.views.generic import ListView, DeleteView
from .models import Todo


class TodoList(ListView):
    model = Todo
    template_name = 'todos.html'

def add_todo(request):
    if request.method=='POST':
        name = request.POST['name']
        place = request.POST['place']
        due_date = request.POST['date']
        todo = Todo.objects.create(name=name, place=place, due_date=due_date)
        return redirect('todo:list')
    return render(request, 'todos.html',)


class TodoDelete(DeleteView):
    model = Todo
    success_url = '/'

django_todo_app/templates/todos.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <style>
      body{
        background-color: lightskyblue;
        font-family: 'Courier New', Courier, monospace;
        font-weight: 600;;
      }
    </style>
  </head>
  <body>
    <div class="container-fluid">
      <div class="text-center mt-5">
       <h1> ToDo App </h1>
      </div>
      <div class="card p-3">
        <form action="{% url 'todo:add' %}" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-4"><input type="text" name="name" class='form-control' placeholder="title"></div>
            <div class="col-md-4"><input type="text" name="place" class='form-control' placeholder="place"></div>
            <div class="col-md-3"><input type="datetime-local" name="date" class='form-control' placeholder="due date"></div>
            <div class="col-md-1 ml-auto"><input type="submit" value="+" class='form-control btn btn-primary'></div>
          </div>
          
        </form>
        <div>
          {% for todo in todo_list %}
          <div class="row mt-3 p-1 pl-5">
            <div class="card col-md-11 p-1 pl-5">{{todo.name}} @ {{todo.place}} due to {{todo.due_date}}</div>
            <div class="col-md-1">

              <form action="{% url 'todo:delete' todo.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="-" class='form-control btn btn-primary'>
              </form>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>